### ISSUE TITLE
Graphics Copy Error

### ISSUE THREAD

**Issue by ChrisAmstutz** [h8man/TurboTrack2D#1]
Hey Thanks so much for posting this! it really helps as a starting point for a sick psuedo 3D project

Im a complete beginner here but I dropped your project into mine and attempted to play, it works but for some reason the road isnt being generated and is light grey, in the command prompt I get this error;

Graphics.CopyTexture can only copy between same texture format groups (d3d11 base formats: src=27 dst=0)

I do have the universal render pipeline installed, however I uninstalled it (the road then spawns) and I still get the error. I think I've tried just about everything to try and fix it! Did you ever experience this error in making it? 

Thanks so much for your time!

**Comment by h8man** [comment]
Hi,

First I didn't try it with URP, maybe I need to check it.
Second, I had this error. It is saying that texture it wants to copy have different format.
I assume you changed some assets. As I recall sprites should be in RGBA32 format, or it fail.
So try to change your sprite format to reimport it in RGBA32.

This project is far from be usable as is. But at least its a starting point.
Let me know if it helps, or you have any other issue, I will try to fix it.

**Comment by ChrisAmstutz** [comment]
That worked perfectly! Thank you so so much! I thought it was an issue with the road materials (since that wasnt being gerated) but as soon as I made all sprites in the scene RGBA32 it worked! 

Thanks again!
